//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid Booking_id { get; set; }
        public int Booking_number { get; set; }
        public System.Guid Book_id { get; set; }
        public int Bookink_book_count { get; set; }
    
        public virtual Booking_condition Booking_condition { get; set; }
        public virtual Books_Catalog Books_Catalog { get; set; }
    }
}
